### ISSUE TITLE
OpenVPN Dashboard Panel Colors

### ISSUE THREAD

**Issue by beornlake** [CallMeKass/pfSense-palenight#2]
The OpenVPN dashboard sub-headers appear to be unchanged from the base pfSense theme and don't really blend well with the Palenight color scheme:

![Screenshot 2023-04-06-104006](https://user-images.githubusercontent.com/3237644/230430088-292a186d-1ef2-4e3f-bea2-50edfffb95a1.jpg)

If we change this directive at line 601:
```css
.widget .panel-heading {
  background-color: #757575;
}
```

to something like:
```css
.widget .panel-heading {
  background-color: var(--active);
}
```
it ends up looking much nicer:
![Screenshot 2023-04-06-104751](https://user-images.githubusercontent.com/3237644/230431330-4cb7324c-29ae-4a4d-a13c-7b39a0f6eb7f.jpg)
