### ISSUE TITLE
pfSense+ Logo Display Errors

### ISSUE THREAD

**Issue by beornlake** [CallMeKass/pfSense-palenight#3]
Looks like the CSS theme file in pfSense+ 23.01 is ever so slightly different than the one in CE. There are a couple directives to fix the logo colors and positioning in the header.

Currently, this is how the header appears on pfSense+:
![Screenshot 2023-04-06-112500](https://user-images.githubusercontent.com/3237644/230439435-403885ae-caab-4d1c-a564-98e8dd1d03ee.jpg)

Lines 226-241:
```css
.logo-st0 {
  fill: var(--foreground);
}

.logo-st1 {
  fill: var(--foreground);
}

.logo-st2 {
  fill: var(--foreground);
}

.navbar-brand {
  padding: 5px 10px 0 10px;
  line-height: 0.3em;
}
```

Can be replaced with:
```css
.logo-st0, .logo-st1, .logo-st2, .logo-st3, .logo-st4, .logo-st5 {
    fill: var(--foreground);
}

.navbar-brand {
    padding: 5px 10px 0 10px;
    line-height: .3em;
}

.factory.navbar-brand {
    padding-top: 10px;
}
```

This fixes the display problems:
![Screenshot 2023-04-06-112657](https://user-images.githubusercontent.com/3237644/230439855-2a275f57-526c-411b-8ee6-e1ace4407a3c.jpg)
